# Generated by Django 3.2.2 on 2021-05-09 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api_app', '0002_auto_20210509_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_resumption',
            field=models.DateTimeField(default=datetime.date(2021, 5, 9)),
        ),
    ]
