# Generated by Django 3.2.2 on 2021-05-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_api_app', '0003_alter_student_date_of_resumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud_api_app.school'),
        ),
    ]
